# Generated by Django 5.0.7 on 2024-07-15 12:06

import compras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do prato.', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Descrição do prato.', verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do prato.', max_digits=5, verbose_name='Preço')),
                ('imagem', models.ImageField(upload_to=compras.models.caminho_imagem)),
            ],
        ),
    ]
